# Generated by Django 3.2.6 on 2021-09-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='パーキング名')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='画像')),
                ('address', models.CharField(max_length=100, verbose_name='住所')),
                ('distance', models.IntegerField(verbose_name='ゲストハウスからの距離')),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22, verbose_name='緯度')),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22, verbose_name='経度')),
                ('number_of_parking_spaces', models.IntegerField(verbose_name='駐車台数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='追加日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
        ),
    ]
