# Generated by Django 3.2.6 on 2021-09-07 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=15, verbose_name='エリア名')),
            ],
        ),
        migrations.AddField(
            model_name='parking',
            name='area',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='accounts.area'),
        ),
    ]
