# Generated by Django 3.2.6 on 2021-09-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210907_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='charge',
            field=models.IntegerField(default=0, verbose_name='利用料金'),
        ),
    ]
