# Generated by Django 3.2.6 on 2021-11-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_parking_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='map_url',
            field=models.IntegerField(default=0, verbose_name='MAP埋め込みURL'),
        ),
    ]
