# Generated by Django 3.2.6 on 2021-11-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_parking_map_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='map_url',
            field=models.CharField(max_length=700, verbose_name='MAP埋め込みURL'),
        ),
    ]
